config/routes.rb
Rails.application.routes.draw do
  post 'filter/edit'
  post 'choice/new'
  delete 'choice/delete'
  get 'home/index'
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
    has_one :item
end

app/models/filter.rb
class Filter < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    
end

app/models/loadout.rb
class Loadout < ApplicationRecord
    has_many :choices
end

app/models/user.rb
class User < ApplicationRecord
    has_many :loadouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choice_controller.rb
class ChoiceController < ApplicationController
  #
  
  #creates a new choice using parameters [:choice][:quantity], [:choice][:quality] and [:item_id]
  
  def new
    quantity = params[:choice][:quantity]
    quality = params[:choice][:quality]
    item = Item.where("id = #{params[:item_id]}").first
    
    if quantity == ""
      quantity = item.stack_size
    end
    
    if quality == ""
      quality = 100
    end
    
    @choice = Choice.new(item_id: params[:item_id], quantity: quantity, quality: quality, blueprint: params[:choice][:blueprint], loadout_id: 1)
    logger.debug "new choice: #{@choice.attributes.inspect}"
    logger.debug "choice should be valid: #{@choice.valid?}"
    
    if @choice.save
      logger.debug "choice saved and user will be redirected to homepage"
      
    else
      logger.debug "choice NOT saved and user will be redirected to homepage"
      
    end
    
    redirect_to home_index_url
  end
  
  #deletes a choice using parameters [:format] where format is the item_id of the choice to be deleted
  def delete
    id = params[:format]
    @choice = Choice.where("id = #{id}").first
    if @choice.destroy
      logger.debug "choice successfully destroyed"
    else
      logger.debug "Choice NOT successfully destroyed"
    end
    redirect_to home_index_url
  end
  
end

app/controllers/filter_controller.rb
class FilterController < ApplicationController
    
    #changes filter active status to false if it is true and true if it is false
    #uses parameter [:format] where format is the id of the selected filter
    def edit
        
        activated_filter = Filter.where(id: params[:format]).first
        filters = Filter.all
        filters.each do |filter|
            filter.assign_attributes({:active => false})
            if filter.save
                logger.debug "filter successfully updated: #{filter.attributes.inspect}"
            end
        end
        
        if activated_filter.name != "All"
            activated_filter.assign_attributes({:active => true})
            if activated_filter.save
                logger.debug "filter successfully updated: #{activated_filter.attributes.inspect}"
            end
        end
        
        redirect_to home_index_url
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  #sets variables that can be accessed in the index section of the home page
  def index
    @items = Item.all
    @loadout = Loadout.first
    @choices = Choice.all
    @console_string = compile_console_string(@loadout)
    @filters = Filter.all
    @active_filters = Filter.where(active: true)
    @filtered_items = filtered_items(@items, @active_filters)
  end
  
  private
  
  #compiles the console command from the list of choices provided by the user
  # uses the parameter loadout which contains all of the choices selected by the user
  # returns a string
  def compile_console_string(loadout)
    
    console_string = ""
    
    choice_count = 0
    
    loadout.choices.each do |choice|
      choice_count += 1
      item = Item.where(id: choice.item_id).first
      number_of_commands = choice.quantity/item.stack_size
      last_command_remainder = choice.quantity % item.stack_size
      
      if number_of_commands == 0
        number_of_commands = 1
      elsif last_command_remainder > 0
        number_of_commands += 1
      end
      
      count = 0
      
      number_of_commands.times do
        count += 1
        
        console_string += 'giveitem "'
        console_string += "#{item.blueprint_path}"
        console_string += '" '
        
        if count == number_of_commands && last_command_remainder > 0
          console_string += "#{last_command_remainder} #{choice.quality} "
        else
          console_string += "#{item.stack_size} #{choice.quality} "
        end
        
        if choice.blueprint == true
          console_string += "1 | "
        else 
          console_string += "0 | "
        end
        
      end
        
        if choice_count == loadout.choices.count
          console_string.chomp!(' | ')
        end
    end
   
    return console_string
          
  end
  
  #creates a list of items to be displayed based on the active filter
  # takes parameters items (Array) and filters (Array)
  # returns an array of filtered items
  def filtered_items(items, filters)
    filtered_items = []
    items.each do |item|
      filters.each do |filter|
        if item.category == filter.name
          filtered_items.push(item)
        end
      end
    end
    return filtered_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/filter_helper.rb
module FilterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/loadout_helper.rb
module LoadoutHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class= "jumbotron text-center">
    <h1>ARK Survival Evolved Console Command Compiler</h1>
</div>

<div class="row first">
    <div class="col-md-4">
        <h2>Description</h2>
        <ol>
            <li>Pick The items you want</li>
            <li>Choose how many of each item you want</li>
            <li>Choose the quality of the item</li>
            <li>Copy to your clipboard</li>
            <li> Press " ` " when you are in the game to open the console</li>
            <li>Press "ctrl + v" and hit enter</li>
            <li>Play Ark with all of the gear you want</li>
        </ol>
    </div>
    
    <div class= "col-md-7">
       <h2>Console Entry</h2>
       <textarea id="console_string" rows="7" cols="100"><%= @console_string %></textarea>
       <button class="clipboard-btn btn btn-success" data-clipboard-action="copy" data-clipboard-target="#console_string">
       Copy to clipboard
      </button>
    </div>
</div>

<div class= "row second">
    <div class= "col-md-4">
        <h2>Loadout</h2>
        <% @choices.each do |choice|%>
            <% item = @items.where("id = #{choice.item_id}").first %>
            <%= form_for :choice, html: {class: "form-inline"} do |f| %>
                <div class= "col-2"><%= item.name %></div>
            
                <div class="form-group mx-sm-3 mb-2">
                    <label for="quantity">Quantity</label>
                    <%= f.number_field :quantity, :readonly => true, :value => choice.quantity, class: 'form-control'  %>
                </div>
                
                <div class="form-group mx-sm-3 mb-2">
                    <label for="quality">Quality</label>
                    <%= f.number_field :quality, :readonly => true, :value => choice.quality, in: 1...101, class: 'form-control' %>
                </div>
            
                <div class="form-group mx-sm-3 mb-2">
                    <label for="blueprint">Blueprint:</label>
                    <%= choice.blueprint %>
                </div>
                
                <%= link_to "remove", choice_delete_path(choice), method: :delete, class: 'btn btn-danger' %>
                
            <% end %>
        <% end %>
    </div>
    
    <div class= "col-md-7">
        <h2>Items</h2>
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Category
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                <% @filters.each do |filter|%>
                    <% unless filter.active == true%>
                      <li role="presentation"><%= link_to filter.name, filter_edit_path(filter), method: :post %></li>
                    <% end %>
                <% end %>
            </ul>
        </div>
        <% if @active_filters.empty? == true %>
            <% @items.each do |item| %>
                <%= form_for :choice, url: choice_new_path, html: {class:"form-inline"}  do |f| %>
                    
                    <p><%= hidden_field_tag 'item_id', item.id %></p> 
                    <div class= "col-2"><%= item.name %> </div>  
                   
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="quantity">Quantity</label>
                        <%= f.number_field :quantity, :value => 1, min: 1, class: 'form-control'  %>
                    </div>
                    
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="quality">Quality</label>
                        <%= f.number_field :quality, :value => 100, in: 1...101, class: 'form-control' %>
                    </div>
                    
                    <div class="form-check form-check-inline blueprint-div">
                        <%= f.check_box :blueprint, id: "blueprint", class:"form-check-input" %>
                        <label class="form-check-label" for="blueprint">
                            Blueprint
                        </label>
                    </div>
                    <%= f.submit "select", class: 'btn btn-success mb-2' %>
                <% end %>
            <% end %>
        <% else%>  
            <% @filtered_items.each do |item| %>
                <%= form_for :choice, url: choice_new_path, html: {class:"form-inline"}  do |f| %>
                   <p><%= hidden_field_tag 'item_id', item.id %></p> 
                   <div class= "col-2"><%= item.name %> </div>  
                   
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="quantity">Quantity</label>
                        <%= f.number_field :quantity, :value => 1, min: 1, class: 'form-control'  %>
                    </div>
                    
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="quality">Quality</label>
                        <%= f.number_field :quality, :value => 100, in: 1...100, class: 'form-control' %>
                    </div>
                    
                    <div class="form-check form-check-inline blueprint-div">
                        <%= f.check_box :blueprint, id: "blueprint", class:"form-check-input" %>
                        <label class="form-check-label" for="blueprint">
                            Blueprint
                        </label>
                    </div>
                    <%= f.submit "select", class: 'btn btn-success mb-2' %>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ark Console Command Compiler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  
<%= yield %>

</body>
</html>